---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: collectorshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: collector
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "600m"
          # On vérifie juste si le port est ouvert, c'est infaillible
          startupProbe:
            tcpSocket:
              port: 5672
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5672
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5672
            periodSeconds: 30
      volumes:
        - name: rabbitmq-data
          emptyDir: {}
        - name: rabbitmq-logs
          emptyDir: {}
        - name: rabbitmq-tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: collectorshop
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
    - name: management
      port: 15672
