---
name: Validation des fichiers Kubernetes

# Se déclenche à chaque fois que tu pousses du code ou fais une Pull Request
"on":
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]

jobs:
  validate-yaml:
    name: Vérification YAML & Kubernetes
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code de ton dépôt
      - name: Checkout du code
        uses: actions/checkout@v4

      # 2. Vérifie la syntaxe YAML de base
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .

      # 3. Vérifie la validité des manifests Kubernetes
      - name: Validation Kubernetes (Kubeconform)
        run: |
          KUBECONFORM_URL="https://github.com/yannh/kubeconform/releases/latest/download/"
          KUBECONFORM_URL="${KUBECONFORM_URL}kubeconform-linux-amd64.tar.gz"
          curl -sSL "$KUBECONFORM_URL" -o kubeconform.tar.gz
          tar -xzf kubeconform.tar.gz kubeconform
          chmod +x kubeconform
          ./kubeconform \
            -summary \
            -kubernetes-version 1.34.6 \
            -ignore-missing-schemas \
            backend.yaml frontend.yaml hpa.yaml mssql.yaml \
            notifications.yaml rabbitmq.yaml namespace.yaml \
            cluster-issuer.yaml

      - name: Scan de sécurité Kubernetes (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
